### ISSUE TITLE
Localization

### ISSUE THREAD

**Issue by vptcnt** [NextFaze/flutter_manup#11]
Hello,

How is it possible to translate texts for the different dialogs ? message and button texts...

Thanks

**Comment by it-sam** [comment]
Use below method to listen ManUpStatus changes
```
@override
  void manUpStatusChanged(ManUpStatus status) {} 
```
In method
Use `ManupAppDialog` class object to show dialog.

```
Future<bool> showAlertDialog(
      {String message = " ",
      String trueText = "ok",
      String falseText,
      bool barrierDismissible = false,
      @required BuildContext context}) {}
```
