### ISSUE TITLE
Allow manup to continue if platform undefined

### ISSUE THREAD

**Issue by grantbrown-adl** [NextFaze/flutter_manup#22]
Currently if a platform is not defined within the json file manup will show as 'unsupported' pushing an overlay onto the screen. 
This will not be able to be removed until json file is edited to include platform details.  

Fix: If json doesn't include platform, define it as latest version as this will allow application to continue. If left as unsupported app will be unusable until platform is defined within json file.

**Comment by zbarbuto** [comment]
Released in 4.0.0
